// src/app/components/users-list/users-list.component.ts
import { Component } from '@angular/core';
import { Observable } from 'rxjs';
import { User } from 'src/app/models/user';
import { UserService } from 'src/app/services/user.service';

@Component({
  selector: 'app-users-list',
  templateUrl: './users-list.component.html',
  styleUrls: ['./users-list.component.scss'],
})
export class UsersListComponent {
  constructor(private userService: UserService) {}

  users$: Observable<User[]> = this.userService.findAll();
}

<div class="card-body">
  <table class="table table-bordered table-striped">
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Name</th>
        <th scope="col">Email</th>
        <th scope="col" class="centered">Actions</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let user of users$ | async">
        <td>{{ user.id }}</td>
        <td>{{ user.name }}</td>
        <td>
          <a href="mailto:{{ user.email }}">{{ user.email }}</a>
        </td>
        <td>
          <div class="group" role="toolbar" aria-label="Basic example">
            <button
              title="Update"
              [octicon]="{ key: 'pencil' }"
              type="button"
              class="btn btn-light no-bg"
              routerLink="{{ user.id }}"
            >
              Update
            </button>
            <button
              title="Delete"
              [octicon]="{ key: 'trash', color: 'white' }"
              type="button"
              class="btn btn-danger"
            >
              Delete
            </button>
          </div>
        </td>
      </tr>
    </tbody>
  </table>
</div>

// src/react/components/UsersList/UsersList.tsx
import React from "react";
import { useUsers } from "../../hooks/user-hook";
import { UsersListItem } from "./UsersListItem";

export const UsersList = () => {
  const { users, deleteUser } = useUsers();
  return (
    <div className="card-body">
      <table className="table table-bordered table-striped">
        <thead className="thead-dark">
          <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Email</th>
            <th scope="col" className="centered">
              Actions
            </th>
          </tr>
        </thead>
        <tbody>
          {users?.map((user) => (
            <UsersListItem key={user.id} user={user} deleteUser={deleteUser} />
          ))}
        </tbody>
      </table>
    </div>
  );
};
