// src/react/components/UserForm/index.tsx
import React, { FormEvent, FunctionComponent, useState } from "react";
import { useLoaderData, useNavigate } from "react-router-dom";
import { User } from "src/app/models/user";
import { saveUser, updateUser } from "src/react/hooks/use-fetch";
import { useUsers } from "src/react/hooks/user-hook";

export const UserFormConnected = () => {
  const user: User = useLoaderData() as User;
  const { refreshData } = useUsers();
  return <UserForm user={user} refreshData={refreshData} />;
};

interface Props {
  user?: User;
  refreshData?: () => Promise<void>;
}
export const UserForm: FunctionComponent<Props> = ({ user, refreshData }) => {
  const [formState, setFormState] = useState({
    name: user?.name,
    email: user?.email,
  });
  const navigate = useNavigate();
  const { name, email } = formState;
  const validName = !!name;
  const validEmail = !!email && email.includes("@");
  const validForm = validEmail && validName;
  const handleSubmit = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const payload = new User(name, email);
    if (!user) {
      await saveUser(payload);
    } else {
      await updateUser(payload, user.id);
    }
    refreshData?.().then(() => navigate("/users"));
  };
  return (
    <div className="card my-5">
      <div className="card-body">
        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label htmlFor="name">Name</label>
            <input
              type="text"
              defaultValue={name}
              // [(ngModel)]="user.name"
              className="form-control"
              id="name"
              name="name"
              placeholder="Enter your name"
              required
              onChange={(e) => setFormState({ email, name: e.target.value })}
              // #name="ngModel"
            />
          </div>
          <div
            hidden={name === undefined || (!!name && validName)}
            className="alert alert-danger"
          >
            Name is required
          </div>
          <div className="form-group">
            <label htmlFor="email">Email</label>
            <input
              type="text"
              defaultValue={email}
              className="form-control"
              id="email"
              name="email"
              placeholder="Enter your email address"
              required
              onChange={(e) => setFormState({ name, email: e.target.value })}
            />
            <div
              hidden={email === undefined || (!!email && validEmail)}
              className="alert alert-danger"
            >
              Email is required
            </div>
          </div>
          <button type="submit" disabled={!validForm} className="btn btn-info">
            {user ? "Update" : "Submit"}
          </button>
        </form>
      </div>
    </div>
  );
};

// src/app/components/user-form/user-form.component.ts
import { Component, Input } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { User } from 'src/app/models/user';
import { UserService } from 'src/app/services/user.service';

@Component({
  selector: 'app-user-form',
  templateUrl: './user-form.component.html',
  styleUrls: ['./user-form.component.scss'],
})
export class UserFormComponent {
  user: User = new User();
  @Input() userDefault: User | null = null;
  constructor(
    private route: ActivatedRoute,
    private router: Router,
    private userService: UserService
  ) {}

  ngOnInit(): void {
    if (this.userDefault) {
      this.user = this.userDefault;
    }
  }

  onSubmit() {
    let obs = this.userService.save(this.user);
    if (this.userDefault) {
      obs = this.userService.update(this.user.id!, this.user);
    }
    firstValueFrom(obs).then(() => this.gotoUserList());
  }

  private gotoUserList() {
    this.router.navigate(['/users']);
  }
}

<div class="card my-5">
  <div class="card-body">
    <form (ngSubmit)="onSubmit()" #userForm="ngForm">
      <div class="form-group">
        <label for="name">Name</label>
        <input
          type="text"
          [(ngModel)]="user.name"
          class="form-control"
          id="name"
          name="name"
          placeholder="Enter your name"
          required
          #name="ngModel"
        />
      </div>
      <div
        [hidden]="name.pristine || (!name.pristine && name.valid)"
        class="alert alert-danger"
      >
        Name is required
      </div>
      <div class="form-group">
        <label for="email">Email</label>
        <input
          type="text"
          [(ngModel)]="user.email"
          class="form-control"
          id="email"
          name="email"
          placeholder="Enter your email address"
          required
          #email="ngModel"
        />
        <div
          [hidden]="email.pristine || (!email.pristine && email.valid)"
          class="alert alert-danger"
        >
          Email is required
        </div>
      </div>
      <button
        type="submit"
        [disabled]="!userForm.form.valid"
        class="btn btn-info"
      >
        {{ userDefault ? "Update" : "Submit" }}
      </button>
    </form>
  </div>
</div>
